// SPDX-License-Identifier: MIT
// The five actors the harness plays, loaded from the git-ignored keyset generated by
// `node scripts/wallets.mjs`. Keys live only in Node (the headless wallet never ships one to the page)
// and are never logged — `describeActors()` prints addresses only.

import { existsSync, readFileSync } from "node:fs";
import { WALLETS_PATH } from "./env";

export const ROLES = ["CREATOR_A", "CREATOR_B", "ASKER_1", "ASKER_2", "ASKER_3"] as const;
export type Role = (typeof ROLES)[number];

export interface Actor {
  role: Role;
  /** HD index (m/44'/60'/0'/0/index) within the harness mnemonic. */
  index: number;
  address: `0x${string}`;
  privateKey: `0x${string}`;
}

export type Actors = Record<Role, Actor>;

interface KeysetFile {
  chainId: number;
  createdAt: string;
  mnemonic: string;
  actors: Record<string, { index: number; address: `0x${string}`; privateKey: `0x${string}` }>;
}

/** Load the keyset, or `null` when it hasn't been generated yet (the specs then skip with a hint). */
export function loadActors(): Actors | null {
  if (!existsSync(WALLETS_PATH)) return null;
  const file = JSON.parse(readFileSync(WALLETS_PATH, "utf8")) as KeysetFile;
  const actors = {} as Actors;
  for (const role of ROLES) {
    const entry = file.actors[role];
    if (!entry) return null;
    actors[role] = { role, ...entry };
  }
  return actors;
}

/** The askers — the actors that must hold testnet USDC. */
export const ASKER_ROLES = ["ASKER_1", "ASKER_2", "ASKER_3"] as const satisfies readonly Role[];

/** A one-line-per-actor address listing (no keys, ever). */
export function describeActors(actors: Actors): string {
  return ROLES.map((role) => `  ${role.padEnd(11)} ${actors[role].address}`).join("\n");
}
